const donatorsList = [
    "SkyStep",
    "qqwref",
    "c0wmanglr",
    "goodevening",
    "XLII",
    "VanillaGawr",
    "Blueoanaoa",
    "OCEshadow",
    "iota",
    "MOKA",
    "xsedim"
];

const adminsList = [
    "dphdmn",
    "vovker",
    "daanbe",
    "ivy"
];

const rename_map = {
    'daanbe': 'ivy',
    'iota': 'skye',
    'ben1996123': 'eggben',
    'sq': 'eskiu',
    'Rafael': 'HashPanda',
    'wiserboblouis': 'wiser',
    'gr21xx': 'garyx',
    'ekim': 'ekimmy',
    'ap_web': 'ap',
    'asdfghqwerty': 'juunas',
    'MegaminX': 'minsie',
    'yzx': '554',
    'JonasCuber11': 'JonasCuber10',
    'Dreamer': 'DreamerTheWolfFox',
    'Zip': 'fuenfeck',
    'Dawidluna': 'Emi',
    'JZE_alt': 'JZE',
    'pluginl': 'redaiyu',
    'ap_guy': 'ap',
    'isaakquing_': 'quing',
    'TheLie谎言': 'dphdmn',
    'Moka雨晞': 'MOKA',
    'diudiuhamburger': '丢丢hamburger',
    'Islamkit': 'IslamKitiev',
    'thelegendary': 'thelegendary08',
    '黑暗报': '636',
    'sqmasep': 'eskiu'

};

function appendFlagIconToNickname(nickname, minimal = false) {
    const lowerCaseNickname = nickname.toLowerCase();
    let country = null;

    for (const user in userCountryMap) {
        if (user.toLowerCase() === lowerCaseNickname) {
            country = userCountryMap[user];
            break;
        }
    }

    if (!country && /[\u4e00-\u9fff\u3400-\u4dbf]/.test(nickname)) {
        country = 'China';
    }

    const flagIconLink = country && countryEmojis[country]
        ? countryEmojis[country]
        : "images/flags/default.png";

    const isDonator = donatorsList.some(donator => donator.toLowerCase() === lowerCaseNickname);

    const donatorIcon = isDonator
        ? `<span class="gold-icon-link"><img class="emoji" draggable="false" alt="gold" src="images/gold.png" style="border-radius:50%"></span>`
        : '';

    const isAdminOrDeveloper = adminsList.some(user => user.toLowerCase() === lowerCaseNickname);

    const roleIcon = isAdminOrDeveloper
        ? `<span class="admin-icon-link">🛠️</span>`
        : '';

    return `<img class="emoji" draggable="false" alt="${country || 'unknown'}" src="${flagIconLink}">${nickname}${roleIcon}${donatorIcon}`;
}

//countries list and emoji for users to add flags

let userCountryMap = {
    Australia: 'Australia',
    Belarus: 'Belarus',
    Belgium: 'Belgium',
    Bulgaria: 'Bulgaria',
    Canada: 'Canada',
    China: 'China',
    Colombia: 'Colombia',
    'Czech Republic': 'Czech Republic',
    Finland: 'Finland',
    France: 'France',
    Germany: 'Germany',
    'Hong Kong': 'Hong Kong',
    India: 'India',
    Italy: 'Italy',
    Malaysia: 'Malaysia',
    Mexico: 'Mexico',
    Netherlands: 'Netherlands',
    Philippines: 'Philippines',
    Poland: 'Poland',
    Russia: 'Russia',
    Serbia: 'Serbia',
    Singapore: 'Singapore',
    Taiwan: 'Taiwan',
    UK: 'UK',
    Japan: 'Japan',
    Ukraine: 'Ukraine',
    USA: 'USA',
    Brazil: 'Brazil',
    Norway: 'Norway',
    'New Zealand': 'New Zealand',
    Indonesia: 'Indonesia',
    Vietnam: 'Vietnam',
    Iceland: 'Iceland',
    Scotland: 'Scotland',
    Slovenia: 'Slovenia',
    'South Africa': 'South Africa',
    Sweden: 'Sweden',
    Afghanistan: 'Afghanistan',
    Albania: 'Albania',
    'American Samoa': 'American Samoa',
    Andorra: 'Andorra',
    Antarctica: 'Antarctica',
    'Antigua and Barbuda': 'Antigua and Barbuda',
    Argentina: 'Argentina',
    Armenia: 'Armenia',
    Aruba: 'Aruba',
    Bermuda: 'Bermuda',
    'Bosnia and Herzegovina': 'Bosnia and Herzegovina',
    Chile: 'Chile',
    'Christmas Island': 'Christmas Island',
    Egypt: 'Egypt',
    Ireland: 'Ireland',
    Kenya: 'Kenya',
    Maldives: 'Maldives',
    Montenegro: 'Montenegro',
    Nepal: 'Nepal',
    Nicaragua: 'Nicaragua',
    Portugal: 'Portugal',
    Switzerland: 'Switzerland',
    'Vatican City': 'Vatican City',
    Yemen: 'Yemen',

    kaxymonoxy: 'Iceland',

    Tronamo: 'Australia',
    Brendan7625: 'Australia',
    lekh2003: 'Australia',
    OCEshadow: 'Australia',
    boink: 'Australia',
    TOOFAST: 'Australia',
    wiserboblouis: 'Australia',
    macandcheese: 'Australia',
    Ton618: 'Australia',
    retsni: 'Australia',
    TeamMathcraft: 'Australia',
    VCP29: 'Australia',
  
    Utochka: 'Belarus',
  
    larsvdb97: 'Belgium',
  
    luybo: 'Bulgaria',
    'v_perm': 'Bulgaria',
    qwerty6450: 'Bulgaria',
    omgplayer: 'Bulgaria',
  
    ap: 'Canada',
    vcuber13: 'Canada',
    yoshinator879: 'Canada',
    Arm0nd0: 'Canada',
    frederick: 'Canada',
  
    Blueoanaoa: 'China',
    JZE: 'China',
    diudiuhamburger: 'China',
    gwj: 'China',
    XMeng: 'China',
    zyc: 'China',
    Ruan: 'China',
    yzx: 'China',
    chy: 'China',
    mochuannnn: 'China',
    '0jacky0': 'China',
    '13975': 'China',
    lzy: 'China',
    lulu: 'China',
    CYY: 'China',
    redaiyu: 'China',
    c4limit3: 'China',
  
    Luisa15: 'Colombia',
    chaeerin: 'Colombia',
  
    Lunarien: 'Czech Republic',
    wrist: 'Czech Republic',
    RZBAKA: 'Czech Republic',
    OgYardel: 'Czech Republic',
  
    asdfghqwerty: 'Finland',
  
    sq: 'France',
    Nikokas: 'France',
    Ladoly: 'France',
    Asbjorn: 'France',
    Netamma: 'France',
    kolunoa: 'France',
    Sarenard: 'France',
    bambinex: 'France',
  
    daanbe: 'Germany',
    XLII: 'Germany',
    dyslexus: 'Germany',
    RedstoneTim: 'Germany',
    Corpllwacquirerrichmf: 'Germany',
    Zip: 'Germany',
    JonasCuber11: 'Germany',
    dani2: 'Germany',
    HawaiiBlue: 'Germany',
    fuenfeck: 'Germany',
  
    Rouxles: 'Hong Kong',
  
    HackerTyper492: 'India',
    krjjod: 'India',
  
    imvelox: 'Italy',
    Nabbissimux: 'Italy',
    DedolCubing: 'Italy',
    chettocri: 'Italy',
    ebrancati: 'Italy',
  
    thelegendary08: 'Malaysia',
  
    gottagitgud: 'Mexico',
  
    Rafael: 'Netherlands',
    JihadCubing: 'Netherlands',
    winteriscool: 'Netherlands',
  
    eff: 'Philippines',
    Enzo1098: 'Philippines',
    usernameh1h2: 'Philippines',
    Nyajumi: 'Philippines',
  
    Dawidluna: 'Poland',
    kiraa96: 'Poland',
    pankubix: 'Poland',
    Verscup: 'Poland',
    Kingstone: 'Poland',
    Dekodzi: 'Poland',
    erykkas: 'Poland',
    bibi100101: 'Poland',
  
    dphdmn: 'Russia',
    vovker: 'Russia',
    goodevening: 'Russia',
    quing: 'Russia',
    OsipovAleksander: 'Russia',
    GoldenBoy: 'Russia',
    IslamKitiev: 'Russia',
    Wrabbable: 'Russia',
    kv1nk: 'Russia',
    gontod195: 'Russia',
    YanikusGG: 'Russia',
    Antonyme: 'Russia',
    thetskerp: 'Russia',
    VyacheslavPervushin: 'Russia',
    vedroboev: 'Russia',
    dima: 'Russia',
    '1210': 'Russia',
    VanillaGawr: 'Russia',
    moceke: 'Russia',
    vmejion: 'Russia',
  
    jug: 'Serbia',
    andrewtheslider: 'Serbia',
  
    peaceknight05: 'Singapore',
    BollnKK: 'Singapore',
    allenbot: 'Singapore',
    MegaminX: 'Singapore',

    gr21xx: 'Slovenia',
  
    SunOceanBeach: 'Taiwan',
  
    ben1996123: 'UK',
    Tree: 'UK',
    TDM: 'UK',
    Billabob: 'UK',
    sameer: 'UK',
    chbld: 'UK',
    JL586: 'UK',
    Garfologist: 'UK',
    darkanturian: 'UK',
    billzo: 'UK',
    Shadowslice: 'UK',
    Berkmann18: 'UK',
    sam596: 'UK',
    luca: 'UK',
    iota: 'UK',
    Waldi: 'UK',
    '2017HARR08': 'UK',
  
    HoHo: 'Japan',
    Ncuber: 'Japan',
  
    IgorTarasov: 'Ukraine',
    oliynykmax: 'Ukraine',
    faugore: 'Ukraine',
    Notobiv: 'Ukraine',
  
    man142: 'USA',
    Magentawolf27YT: 'USA',
    R14: 'USA',
    xsedim: 'USA',
    TheMatsValk: 'USA',
    tnum10: 'USA',
    SkyStep: 'USA',
    soup: 'USA',
    Scyter: 'USA',
    enigma515: 'USA',
    qqwref: 'USA',
    upvoid: 'USA',
    happydays: 'USA',
    LEBaldy: 'USA',
    strakerak: 'USA',
    c0wmanglr: 'USA',
    mAyo: 'USA',
    teri: 'USA',
    ShyGuy1265: 'USA',
    creepycat18: 'USA',
    Ianwubby: 'USA',
    BindeDSA: 'USA',
    Sethamajig: 'USA',
    MLGSheep1: 'USA',
    BrickInAPresent: 'USA',
    Owen: 'USA',
    Dapianokid: 'USA',
    Dreamer: 'USA',
    '105iqengineer': 'USA',
    Alex: 'USA',
    alka: 'USA',
    kleb: 'USA',
    HOGGYSIMP: 'USA',
    amazingpikachu37: 'USA',
    zach: 'USA',
    July2nd: 'USA',
    robotmania: 'USA',
    Alumina: 'USA',
    Spliffey: 'USA',
    zander: 'USA',
    xishu: 'USA',
    justnnotyou: 'USA',
    BrethrenBeef: 'USA',
    MOKA: 'USA',
    theepossum: 'USA',
    ryan5: 'USA',
    WillTRM: 'USA',
    clementinebedsheets: 'USA',
    lopsidedhampter: 'USA',
    '2023RAMA09': 'USA',
    Chanoh17: 'USA',
  
    Sakinuto: 'Brazil',
    PedroAM: 'Brazil',
  
    Yiclaw: 'Norway',
  
    majesticwalrus: 'New Zealand',
  
    Berries1111: 'Indonesia',
  
    hkg11khanh: 'Vietnam',
    Duysen: 'Vietnam',
    nguywn: 'Vietnam',

    zynua: 'South Africa',
    Yokow: 'South Africa',

    xenia: 'Sweden',
    Andersh2345: 'Sweden',

    TheGameChallenger: 'Afghanistan',

    // LM country data
    '_1791': 'China',
    '106229': 'Ukraine',
    '127852': 'Russia',
    '1919810': 'China',
    '2021ZHAN34': 'China',
    '2191455001': 'China',
    '24201': 'China',
    '388089': 'Argentina',
    '3blue1blue': 'China',
    '41679': 'China',
    '42i196': 'China',
    '546v菌': 'USA',
    '554': 'China',
    '629moonlight': 'China',
    '636': 'China',
    '76533': 'China',
    '77再也不要nf': 'China',
    'A33001': 'China',
    'abcdhhhh': 'China',
    'abcwx': 'China',
    'aiktus': 'China',
    'aky': 'China',
    'Anonymous': 'China',
    'APR': 'China',
    'Arola': 'China',
    'Arskynal': 'China',
    'ASHL': 'China',
    'askk': 'China',
    'ax0292': 'China',
    'bg': 'China',
    'bili丶那就睡觉': 'China',
    'boru': 'Poland',
    'brick': 'USA',
    'Browchik': 'Ukraine',
    'Caozj': 'China',
    'castle123': 'China',
    'cjy': 'China',
    'Coleslaw': 'Canada',
    'creepercube': 'China',
    'CUBERK': 'China',
    'Cuberlgy': 'China',
    'cuberlq': 'China',
    'Cuber白夜': 'China',
    'Cuber阳': 'China',
    'CX330｀': 'China',
    'cyb': 'China',
    'D0ggy': 'China',
    'D72': 'Maldives',
    'dcy': 'China',
    'DDMM': 'China',
    'DengStar': 'China',
    'djdnjr': 'China',
    'dms': 'China',
    'Dokarasuri': 'China',
    'Doukidt': 'China',
    'downvoid': 'USA',
    'DPr': 'China',
    'DpX': 'China',
    'Durm.': 'China',
    'Ecstasy疯癫': 'China',
    'Emi': 'Poland',
    'ENILINE': 'China',
    'fbd35050': 'China',
    'FENG.Z': 'China',
    'Fengchu': 'China',
    'flextrek': 'China',
    'FreeWill': 'China',
    'FrozenMN': 'China',
    'frsdnf': 'China',
    'G38016': 'China',
    'hanchebj期待再次': 'China',
    'hexd923': 'China',
    'hmq': 'China',
    'Hydrofficial': 'China',
    'IAA': 'Italy',
    'Infinitume': 'China',
    'InvictusX': 'China',
    'ioo_': 'China',
    'ittfia': 'China',
    'JellyFish': 'China',
    'JRJ': 'China',
    'jrjtql': 'China',
    'jsia': 'China',
    'Jur105': 'China',
    'JWRRRR': 'China',
    'JXY.': 'China',
    'K2Mg': 'Netherlands',
    'khahn': 'USA',
    'km2008': 'China',
    'Koi': 'USA',
    'Kone_': 'China',
    'Kt': 'China',
    'kujojotaro': 'China',
    'kviolety': 'China',
    'layer': 'Afghanistan',
    'liang.': 'China',
    'Light': 'China',
    'LLH': 'China',
    'Love_cant': 'China',
    'MaksDark': 'Russia',
    'Methano1': 'China',
    'MFJ水循环': 'China',
    'MIDNIGHTS': 'China',
    'MitchellMeng': 'China',
    'mniljp': 'China',
    'Moka雨晞': 'USA',
    'momoyu': 'China',
    'Monstercat': 'China',
    'mthhhhhh': 'China',
    'Mudkip413个9': 'China',
    'MUSIC_LOVER': 'China',
    'mystrimo345': 'Nepal',
    'NH4NO2': 'China',
    'OP': 'Japan',
    'past.SHcTo': 'China',
    'pkc': 'China',
    'PLAYER1': 'China',
    'Player101728': 'China',
    'Player123588': 'Canada',
    'Player27415': 'China',
    'Player77936': 'China',
    'Player78140': 'China',
    'Player85190': 'China',
    'player99102': 'China',
    'pluginl': 'China',
    'S_': 'China',
    'sadcssz的粉丝': 'China',
    'Salt': 'China',
    'Samarra': 'China',
    'Sawtheb': 'China',
    'SBGLuck': 'China',
    'Seisen_Star': 'China',
    'Sept.': 'China',
    'Serol': 'China',
    'shakal1111': 'Russia',
    'SHcTo': 'China',
    'shintiii': 'China',
    'shitlike': 'China',
    'shl': 'China',
    'sk时空猎人lr': 'China',
    'Slavomilka': 'Russia',
    'Smebun': 'China',
    'SpaceX': 'China',
    'SparkRTG': 'China',
    'SSG': 'China',
    'sugarcane': 'China',
    'Summer.': 'China',
    'SundayTetris': 'China',
    'sunflower': 'China',
    'SunSeaBeach': 'China',
    'sun的ice': 'China',
    'suwjshan': 'China',
    'Tardigrade': 'China',
    'The43Office': 'China',
    'thelegendary': 'Malaysia',
    'The三四Office': 'China',
    'ToOm00r1n': 'China',
    'VDSX': 'China',
    'vicissitude': 'China',
    'Voyager': 'Russia',
    'VPerm': 'Bulgaria',
    'wawawawawaw': 'Nicaragua',
    'wld': 'China',
    'WLF117171711': 'China',
    'WYB.MX': 'China',
    'WZ.': 'China',
    'xfx': 'Montenegro',
    'xhskoa': 'China',
    'xhzzzz': 'China',
    'ximuximu': 'China',
    'xzy': 'China',
    'x知心x': 'China',
    'Yan彦': 'China',
    'YC小火柴': 'China',
    'yhx追寻本心': 'China',
    'Yin': 'China',
    'ylsa': 'China',
    'yqtx': 'China',
    'zero.13平常心': 'China',
    'Zh0uKal1': 'China',
    'ZhangHB': 'China',
    'zsmklmy': 'China',
    'zwh': 'China',
    'ZYCl': 'China',
    'zzy': 'China',
    '一个快乐的魔方宅': 'China',
    '一只小菜鸟': 'China',
    '不找': 'China',
    '丰丰': 'China',
    '举帝_official': 'China',
    '乌米玲': 'China',
    '九肆': 'Malaysia',
    '二狗子哟丶': 'China',
    '云泽': 'China',
    '亦辰': 'China',
    '人生无愿无梦': 'China',
    '似了': 'China',
    '低智商协会会长': 'China',
    '余余': 'China',
    '偏安一隅': 'China',
    '全场唯一真爆米花': 'Australia',
    '再进步一点': 'China',
    '冰瓜豪': 'China',
    '冰美4cOff33': 'China',
    '冷饭': 'China',
    '初心者': 'Japan',
    '前尘隔海': 'China',
    '剑圣': 'China',
    '勒紧的睿': 'China',
    '包包bkx': 'China',
    '北北北北北': 'China',
    '北嶋彻': 'China',
    '北纬线': 'China',
    '匿名機器人': 'China',
    '十五的月亮': 'China',
    '千早爱音': 'China',
    '厉害不': 'China',
    '又栖': 'China',
    '反应式': 'China',
    '取个什么名字': 'China',
    '叨叨yia': 'China',
    '只会co': 'China',
    '只识弯弓射沙雕': 'China',
    '可以叫我张小兴': 'China',
    '可观测宇宙第一名': 'China',
    '右耳': 'China',
    '吉尔加美食': 'China',
    '向43求爱': 'Japan',
    '君君CYY': 'China',
    '听见': 'China',
    '周九日': 'China',
    '咖啡猫永远喜欢艺': 'Japan',
    '喝稀饭的疯子': 'China',
    '四起': 'China',
    '因为夏日将终': 'China',
    '墨言鹰': 'China',
    '大雾不见赤霄': 'China',
    '天边飘小雪': 'China',
    '奖励自己': 'China',
    '她与狙皆失': 'China',
    '好心人1314': 'China',
    '妖帝神逆': 'China',
    '威廉麦克白': 'China',
    '孙小川': 'China',
    '宁夏第一酒神': 'China',
    '宇宙巡航者': 'China',
    '宇文锦辰': 'China',
    '宾阼10': 'China',
    '寒玥清影': 'China',
    '小为本为': 'China',
    '小小苏': 'China',
    '小星星317': 'China',
    '小童没话': 'China',
    '小羊肖恩': 'China',
    '小萌老公': 'China',
    '小黑菌': 'China',
    '就此别过': 'China',
    '山西男桐': 'China',
    '岚棂': 'China',
    '已连接': 'China',
    '帐号已注销': 'China',
    '席离突然': 'China',
    '幻e': 'Portugal',
    '引爆米花町': 'China',
    '弗利萨': 'China',
    '张三': 'China',
    '张茗杰': 'China',
    '弹指越千程': 'China',
    '快乐的啦啦啦啦啦啦': 'China',
    '快乐的电报机': 'China',
    '快进到我再也不玩抽象了': 'China',
    '念念': 'China',
    '念风月': 'China',
    '怪盗基德': 'China',
    '愿仔': 'China',
    '愿子': 'China',
    '愿我可': 'China',
    '慕斯331': 'China',
    '憨憨的破忒头': 'China',
    '我不是新手': 'China',
    '我去不早说': 'China',
    '我和球ssd': 'China',
    '我欲成仙': 'Vietnam',
    '我见枯朽之后': 'China',
    '手残van家': 'China',
    '执手相看泪眼': 'China',
    '扫不出来的fyb': 'China',
    '扫雷Z级选手': 'China',
    '抛抛掉': 'China',
    '择浩留': 'China',
    '拾玖不食酒': 'Germany',
    '数人世相逢': 'China',
    '数字华容道': 'China',
    '文艺复兴选手': 'China',
    '无双不等于无敌': 'China',
    '无敌战神': 'China',
    '无语159': 'China',
    '无边': 'China',
    '旧人lzy': 'China',
    '时落': 'China',
    '明远': 'China',
    '星星枫叶': 'China',
    '晴陌_': 'China',
    '暂退的3blue突然': 'China',
    '暗黑': 'China',
    '木俞': 'China',
    '木已臣舟': 'China',
    '本昵称已被占': 'China',
    '朱嘉俊': 'China',
    '朱学伟': 'China',
    '林辣条': 'China',
    '果冻啊QAQ': 'China',
    '某COPY的ncf': 'China',
    '梅轩宇': 'China',
    '梦里落襯': 'China',
    '榆木的木': 'China',
    '櫂_CZR': 'China',
    '欣欣欣': 'China',
    '毛毛虫': 'China',
    '氢锂硅矾': 'China',
    '水深dw': 'China',
    '永远喜欢八奈见大人': 'China',
    '永雏塔菲': 'China',
    '汉水皮皮': 'China',
    '江文': 'China',
    '江洋': 'Ukraine',
    '没手机的问题儿童': 'China',
    '没电脑的问题儿童': 'China',
    '没赢过': 'China',
    '泽树': 'China',
    '海绵宝宝你给我挺起头来': 'China',
    '涩皮': 'China',
    '深海舌鲆鱼': 'China',
    '温如Enid': 'China',
    '熬夜小能手好像': 'China',
    '爆炒猪心': 'China',
    '爆米花': 'China',
    '爱德华': 'China',
    '牢万劫': 'China',
    '独爱万疆': 'China',
    '狼宝22094': 'China',
    '猎户星座的木星人': 'China',
    '猥琐男': 'China',
    '猫猫猫': 'China',
    '玉米烙小狗': 'China',
    '王小桃': 'China',
    '略明朝': 'China',
    '白开水拯救世界': 'China',
    '皇室变态12本': 'China',
    '砂糖': 'China',
    '祝望': 'China',
    '神里绫华的光': 'China',
    '祺.': 'China',
    '离线用户': 'China',
    '秋昂': 'China',
    '穆阳文': 'China',
    '空愿': 'China',
    '空里流霜丷': 'China',
    '空雨': 'China',
    '笙萧Fs': 'China',
    '笨比胖子': 'China',
    '笨笨还在做题': 'China',
    '笼子7': 'China',
    '筛沨': 'China',
    '粥粥包子': 'China',
    '綵荳': 'China',
    '绝望的七重奏': 'China',
    '老年人玩家': 'China',
    '耿诡': 'China',
    '聆竹听风': 'China',
    '肆陆壹贰': 'China',
    '肥鱼': 'China',
    '自信且阿轩': 'China',
    '舒尔特': 'China',
    '舞萌断网我恨你': 'China',
    '舟臣': 'China',
    '色戒大师': 'China',
    '芒芒甘露': 'China',
    '莫诞9': 'China',
    '菜得抠jio': 'China',
    '菜鸟逐梦': 'China',
    '蒙奇D黄猿': 'China',
    '薯条怪': 'China',
    '行云': 'China',
    '行简': 'China',
    '袅殇': 'China',
    '襯落': 'China',
    '译翼飞鸾': 'China',
    '负功': 'China',
    '负辞': 'China',
    '轩轩': 'China',
    '软软的爆米花': 'China',
    '轻辞浅梨白': 'China',
    '载梦长歌': 'China',
    '边玩卫队猪边拧魔方': 'China',
    '这恒河里': 'China',
    '这辈子不可能sub40': 'China',
    '违规账号': 'China',
    '退游的ljzzzz竟然': 'China',
    '退游的退游的退游的竟然': 'China',
    '逍遥晓梦迷蝴蝶': 'China',
    '遗怡': 'China',
    '那一天的安康安康不起来': 'China',
    '那现在你要怎么做呢': 'UK',
    '郈琏702': 'China',
    '配极': 'China',
    '酱香的爆米花': 'China',
    '钔锌': 'China',
    '问问絕弒好不好': 'China',
    '阳和Annuus': 'China',
    '阿米巴': 'China',
    '阿紫猫猫': 'China',
    '随星': 'China',
    '霜晨的狂热粉丝': 'China',
    '青歌丶': 'China',
    '非洲萌': 'China',
    '非自': 'China',
    '鞠泽恩': 'China',
    '音游老怪物': 'China',
    '驴花': 'China',
    '高才森': 'China',
    '鱼形诡迹': 'China',
    '鳄羊羊': 'China',
    '鸩书': 'China',
    '鸽者': 'China',
    '黑暗报': 'China',
    '黯九': 'China',
    '齐天大圣': 'China',
    '龙吟': 'China',

  };

  

const countryEmojis = {
    Indonesia: 'images/flags/Indonesia.png',
    Australia: 'images/flags/Australia.png',
    Belarus: 'images/flags/Belarus.png',
    Belgium: 'images/flags/Belgium.png',
    Bulgaria: 'images/flags/Bulgaria.png',
    Canada: 'images/flags/Canada.png',
    China: 'images/flags/China.png',
    Colombia: 'images/flags/Colombia.png',
    'Czech Republic': 'images/flags/Czech-Republic.png',
    Finland: 'images/flags/Finland.png',
    France: 'images/flags/France.png',
    Germany: 'images/flags/Germany.png',
    'Hong Kong': 'images/flags/Hong-Kong.png',
    India: 'images/flags/India.png',
    Italy: 'images/flags/Italy.png',
    Malaysia: 'images/flags/Malaysia.png',
    Mexico: 'images/flags/Mexico.png',
    Netherlands: 'images/flags/Netherlands.png',
    Philippines: 'images/flags/Philippines.png',
    Poland: 'images/flags/Poland.png',
    Russia: 'images/flags/Russia.png',
    Serbia: 'images/flags/Serbia.png',
    Singapore: 'images/flags/Singapore.png',
    Taiwan: 'images/flags/Taiwan.png',
    'UK': 'images/flags/United-Kingdom.png',
    Japan: 'images/flags/Japan.png',
    Ukraine: 'images/flags/Ukraine.png',
    'USA': 'images/flags/United-States.png',
    Brazil: 'images/flags/Brazil.png',
    Norway: 'images/flags/Norway.png',
    'New Zealand': 'images/flags/New-Zealand.png',
    Vietnam: 'images/flags/Vietnam.png',
    Abkhazia: 'images/flags/Abkhazia.png',
    Afghanistan: 'images/flags/Afghanistan.png',
    Aland: 'images/flags/Aland.png',
    Albania: 'images/flags/Albania.png',
    Algeria: 'images/flags/Algeria.png',
    'American Samoa': 'images/flags/American-Samoa.png',
    Andorra: 'images/flags/Andorra.png',
    Angola: 'images/flags/Angola.png',
    Anguilla: 'images/flags/Anguilla.png',
    Antarctica: 'images/flags/Antarctica.png',
    'Antigua and Barbuda': 'images/flags/Antigua-and-Barbuda.png',
    Argentina: 'images/flags/Argentina.png',
    Armenia: 'images/flags/Armenia.png',
    Aruba: 'images/flags/Aruba.png',
    Australia: 'images/flags/Australia.png',
    Austria: 'images/flags/Austria.png',
    Azerbaijan: 'images/flags/Azerbaijan.png',
    Bahamas: 'images/flags/Bahamas.png',
    Bahrain: 'images/flags/Bahrain.png',
    Bangladesh: 'images/flags/Bangladesh.png',
    Barbados: 'images/flags/Barbados.png',
    'Basque Country': 'images/flags/Basque-Country.png',
    Belarus: 'images/flags/Belarus.png',
    Belgium: 'images/flags/Belgium.png',
    Belize: 'images/flags/Belize.png',
    Benin: 'images/flags/Benin.png',
    Bermuda: 'images/flags/Bermuda.png',
    Bhutan: 'images/flags/Bhutan.png',
    Bolivia: 'images/flags/Bolivia.png',
    'Bosnia and Herzegovina': 'images/flags/Bosnia-and-Herzegovina.png',
    Botswana: 'images/flags/Botswana.png',
    Brazil: 'images/flags/Brazil.png',
    'British Antarctic Territory': 'images/flags/British-Antarctic-Territory.png',
    'British Virgin Islands': 'images/flags/British-Virgin-Islands.png',
    Brunei: 'images/flags/Brunei.png',
    Bulgaria: 'images/flags/Bulgaria.png',
    'Burkina Faso': 'images/flags/Burkina-Faso.png',
    Burundi: 'images/flags/Burundi.png',
    Cambodia: 'images/flags/Cambodia.png',
    Cameroon: 'images/flags/Cameroon.png',
    Canada: 'images/flags/Canada.png',
    'Canary Islands': 'images/flags/Canary-Islands.png',
    'Cape Verde': 'images/flags/Cape-Verde.png',
    'Cayman Islands': 'images/flags/Cayman-Islands.png',
    'Central African Republic': 'images/flags/Central-African-Republic.png',
    Chad: 'images/flags/Chad.png',
    Chile: 'images/flags/Chile.png',
    China: 'images/flags/China.png',
    'Christmas Island': 'images/flags/Christmas-Island.png',
    'Cocos Keeling Islands': 'images/flags/Cocos-Keeling-Islands.png',
    Colombia: 'images/flags/Colombia.png',
    Commonwealth: 'images/flags/Commonwealth.png',
    Comoros: 'images/flags/Comoros.png',
    'Cook Islands': 'images/flags/Cook-Islands.png',
    'Costa Rica': 'images/flags/Costa-Rica.png',
    "Cote d'Ivoire": 'images/flags/Cote-dIvoire.png',
    Croatia: 'images/flags/Croatia.png',
    Cuba: 'images/flags/Cuba.png',
    Curacao: 'images/flags/Curacao.png',
    Cyprus: 'images/flags/Cyprus.png',
    'Czech Republic': 'images/flags/Czech-Republic.png',
    'Democratic Republic of the Congo': 'images/flags/Democratic-Republic-of-the-Congo.png',
    Denmark: 'images/flags/Denmark.png',
    Djibouti: 'images/flags/Djibouti.png',
    Dominica: 'images/flags/Dominica.png',
    'Dominican Republic': 'images/flags/Dominican-Republic.png',
    'East Timor': 'images/flags/East-Timor.png',
    Ecuador: 'images/flags/Ecuador.png',
    Egypt: 'images/flags/Egypt.png',
    'El Salvador': 'images/flags/El-Salvador.png',
    England: 'images/flags/England.png',
    'Equatorial Guinea': 'images/flags/Equatorial-Guinea.png',
    Eritrea: 'images/flags/Eritrea.png',
    Estonia: 'images/flags/Estonia.png',
    Ethiopia: 'images/flags/Ethiopia.png',
    'European Union': 'images/flags/European-Union.png',
    'Falkland Islands': 'images/flags/Falkland-Islands.png',
    Faroes: 'images/flags/Faroes.png',
    Fiji: 'images/flags/Fiji.png',
    Finland: 'images/flags/Finland.png',
    France: 'images/flags/France.png',
    'French Polynesia': 'images/flags/French-Polynesia.png',
    'French Southern Territories': 'images/flags/French-Southern-Territories.png',
    Gabon: 'images/flags/Gabon.png',
    Gambia: 'images/flags/Gambia.png',
    Georgia: 'images/flags/Georgia.png',
    Germany: 'images/flags/Germany.png',
    Ghana: 'images/flags/Ghana.png',
    Gibraltar: 'images/flags/Gibraltar.png',
    GoSquared: 'images/flags/GoSquared.png',
    Greece: 'images/flags/Greece.png',
    Greenland: 'images/flags/Greenland.png',
    Grenada: 'images/flags/Grenada.png',
    Guam: 'images/flags/Guam.png',
    Guatemala: 'images/flags/Guatemala.png',
    Guernsey: 'images/flags/Guernsey.png',
    'Guinea Bissau': 'images/flags/Guinea-Bissau.png',
    Guinea: 'images/flags/Guinea.png',
    Guyana: 'images/flags/Guyana.png',
    Haiti: 'images/flags/Haiti.png',
    Honduras: 'images/flags/Honduras.png',
    'Hong Kong': 'images/flags/Hong-Kong.png',
    Hungary: 'images/flags/Hungary.png',
    Iceland: 'images/flags/Iceland.png',
    India: 'images/flags/India.png',
    Indonesia: 'images/flags/Indonesia.png',
    Iran: 'images/flags/Iran.png',
    Iraq: 'images/flags/Iraq.png',
    Ireland: 'images/flags/Ireland.png',
    'Isle of Man': 'images/flags/Isle-of-Man.png',
    Israel: 'images/flags/Israel.png',
    Italy: 'images/flags/Italy.png',
    Jamaica: 'images/flags/Jamaica.png',
    Japan: 'images/flags/Japan.png',
    Jersey: 'images/flags/Jersey.png',
    Jordan: 'images/flags/Jordan.png',
    Kazakhstan: 'images/flags/Kazakhstan.png',
    Kenya: 'images/flags/Kenya.png',
    Kiribati: 'images/flags/Kiribati.png',
    Kosovo: 'images/flags/Kosovo.png',
    Kuwait: 'images/flags/Kuwait.png',
    Kyrgyzstan: 'images/flags/Kyrgyzstan.png',
    Laos: 'images/flags/Laos.png',
    Latvia: 'images/flags/Latvia.png',
    Lebanon: 'images/flags/Lebanon.png',
    Lesotho: 'images/flags/Lesotho.png',
    Liberia: 'images/flags/Liberia.png',
    Libya: 'images/flags/Libya.png',
    Liechtenstein: 'images/flags/Liechtenstein.png',
    Lithuania: 'images/flags/Lithuania.png',
    Luxembourg: 'images/flags/Luxembourg.png',
    Macau: 'images/flags/Macau.png',
    Macedonia: 'images/flags/Macedonia.png',
    Madagascar: 'images/flags/Madagascar.png',
    Malawi: 'images/flags/Malawi.png',
    Malaysia: 'images/flags/Malaysia.png',
    Maldives: 'images/flags/Maldives.png',
    Mali: 'images/flags/Mali.png',
    Malta: 'images/flags/Malta.png',
    Mars: 'images/flags/Mars.png',
    'Marshall Islands': 'images/flags/Marshall-Islands.png',
    Martinique: 'images/flags/Martinique.png',
    Mauritania: 'images/flags/Mauritania.png',
    Mauritius: 'images/flags/Mauritius.png',
    Mayotte: 'images/flags/Mayotte.png',
    Mexico: 'images/flags/Mexico.png',
    Micronesia: 'images/flags/Micronesia.png',
    Moldova: 'images/flags/Moldova.png',
    Monaco: 'images/flags/Monaco.png',
    Mongolia: 'images/flags/Mongolia.png',
    Montenegro: 'images/flags/Montenegro.png',
    Montserrat: 'images/flags/Montserrat.png',
    Morocco: 'images/flags/Morocco.png',
    Mozambique: 'images/flags/Mozambique.png',
    Myanmar: 'images/flags/Myanmar.png',
    'Nagorno Karabakh': 'images/flags/Nagorno-Karabakh.png',
    Namibia: 'images/flags/Namibia.png',
    NATO: 'images/flags/NATO.png',
    Nauru: 'images/flags/Nauru.png',
    Nepal: 'images/flags/Nepal.png',
    'Netherlands Antilles': 'images/flags/Netherlands-Antilles.png',
    Netherlands: 'images/flags/Netherlands.png',
    'New Caledonia': 'images/flags/New-Caledonia.png',
    'New Zealand': 'images/flags/New-Zealand.png',
    Nicaragua: 'images/flags/Nicaragua.png',
    Niger: 'images/flags/Niger.png',
    Nigeria: 'images/flags/Nigeria.png',
    Niue: 'images/flags/Niue.png',
    'Norfolk Island': 'images/flags/Norfolk-Island.png',
    'North Korea': 'images/flags/North-Korea.png',
    'Northern Cyprus': 'images/flags/Northern-Cyprus.png',
    'Northern Mariana Islands': 'images/flags/Northern-Mariana-Islands.png',
    Norway: 'images/flags/Norway.png',
    Olympics: 'images/flags/Olympics.png',
    Oman: 'images/flags/Oman.png',
    Pakistan: 'images/flags/Pakistan.png',
    Palau: 'images/flags/Palau.png',
    Palestine: 'images/flags/Palestine.png',
    Panama: 'images/flags/Panama.png',
    'Papua New Guinea': 'images/flags/Papua-New-Guinea.png',
    Paraguay: 'images/flags/Paraguay.png',
    Peru: 'images/flags/Peru.png',
    Philippines: 'images/flags/Philippines.png',
    'Pitcairn Islands': 'images/flags/Pitcairn-Islands.png',
    Poland: 'images/flags/Poland.png',
    Portugal: 'images/flags/Portugal.png',
    'Puerto Rico': 'images/flags/Puerto-Rico.png',
    Qatar: 'images/flags/Qatar.png',
    'Red Cross': 'images/flags/Red-Cross.png',
    'Republic of the Congo': 'images/flags/Republic-of-the-Congo.png',
    Romania: 'images/flags/Romania.png',
    Russia: 'images/flags/Russia.png',
    Rwanda: 'images/flags/Rwanda.png',
    'Saint Barthelemy': 'images/flags/Saint-Barthelemy.png',
    'Saint Helena': 'images/flags/Saint-Helena.png',
    'Saint Kitts and Nevis': 'images/flags/Saint-Kitts-and-Nevis.png',
    'Saint Lucia': 'images/flags/Saint-Lucia.png',
    'Saint Martin': 'images/flags/Saint-Martin.png',
    'Saint Vincent and the Grenadines': 'images/flags/Saint-Vincent-and-the-Grenadines.png',
    Samoa: 'images/flags/Samoa.png',
    'San Marino': 'images/flags/San-Marino.png',
    'Sao Tome and Principe': 'images/flags/Sao-Tome-and-Principe.png',
    'Saudi Arabia': 'images/flags/Saudi-Arabia.png',
    Scotland: 'images/flags/Scotland.png',
    Senegal: 'images/flags/Senegal.png',
    Serbia: 'images/flags/Serbia.png',
    Seychelles: 'images/flags/Seychelles.png',
    'Sierra Leone': 'images/flags/Sierra-Leone.png',
    Singapore: 'images/flags/Singapore.png',
    Slovakia: 'images/flags/Slovakia.png',
    Slovenia: 'images/flags/Slovenia.png',
    'Solomon Islands': 'images/flags/Solomon-Islands.png',
    Somalia: 'images/flags/Somalia.png',
    Somaliland: 'images/flags/Somaliland.png',
    'South Africa': 'images/flags/South-Africa.png',
    'South Georgia and the South Sandwich Islands': 'images/flags/South-Georgia-and-the-South-Sandwich-Islands.png',
    'South Korea': 'images/flags/South-Korea.png',
    'South Ossetia': 'images/flags/South-Ossetia.png',
    'South Sudan': 'images/flags/South-Sudan.png',
    Spain: 'images/flags/Spain.png',
    'Sri Lanka': 'images/flags/Sri-Lanka.png',
    Sudan: 'images/flags/Sudan.png',
    Suriname: 'images/flags/Suriname.png',
    Swaziland: 'images/flags/Swaziland.png',
    Sweden: 'images/flags/Sweden.png',
    Switzerland: 'images/flags/Switzerland.png',
    Syria: 'images/flags/Syria.png',
    Taiwan: 'images/flags/Taiwan.png',
    Tajikistan: 'images/flags/Tajikistan.png',
    Tanzania: 'images/flags/Tanzania.png',
    Thailand: 'images/flags/Thailand.png',
    Togo: 'images/flags/Togo.png',
    Tokelau: 'images/flags/Tokelau.png',
    Tonga: 'images/flags/Tonga.png',
    'Trinidad and Tobago': 'images/flags/Trinidad-and-Tobago.png',
    Tunisia: 'images/flags/Tunisia.png',
    Turkey: 'images/flags/Turkey.png',
    Turkmenistan: 'images/flags/Turkmenistan.png',
    'Turks and Caicos Islands': 'images/flags/Turks-and-Caicos-Islands.png',
    Tuvalu: 'images/flags/Tuvalu.png',
    Uganda: 'images/flags/Uganda.png',
    Ukraine: 'images/flags/Ukraine.png',
    'United Arab Emirates': 'images/flags/United-Arab-Emirates.png',
    'United Kingdom': 'images/flags/United-Kingdom.png',
    'United Nations': 'images/flags/United-Nations.png',
    'United States': 'images/flags/United-States.png',
    Unknown: 'images/flags/Unknown.png',
    Uruguay: 'images/flags/Uruguay.png',
    'US Virgin Islands': 'images/flags/US-Virgin-Islands.png',
    Uzbekistan: 'images/flags/Uzbekistan.png',
    Vanuatu: 'images/flags/Vanuatu.png',
    'Vatican City': 'images/flags/Vatican-City.png',
    Venezuela: 'images/flags/Venezuela.png',
    Vietnam: 'images/flags/Vietnam.png',
    Wales: 'images/flags/Wales.png',
    'Wallis And Futuna': 'images/flags/Wallis-And-Futuna.png',
    'Western Sahara': 'images/flags/Western-Sahara.png',
    Yemen: 'images/flags/Yemen.png',
    Zambia: 'images/flags/Zambia.png',
    Zimbabwe: 'images/flags/Zimbabwe.png',
    cheat: 'images/flags/cheat.png'
};

// Update keys using rename_map (old names -> new names)
for (const username of Object.keys(userCountryMap)) {
    // Find if this username is an old name in rename_map
    for (const [oldName, newName] of Object.entries(rename_map)) {
        if (oldName.toLowerCase() === username.toLowerCase()) {
            const country = userCountryMap[username];
            delete userCountryMap[username];
            // Only set the new name if it doesn't already exist (preserve original mapping)
            if (!(newName in userCountryMap)) {
                userCountryMap[newName] = country;
            }
            break;
        }
    }
}

// Update donatorsList using rename_map (old names -> new names)
for (let i = 0; i < donatorsList.length; i++) {
    for (const [oldName, newName] of Object.entries(rename_map)) {
        if (oldName.toLowerCase() === donatorsList[i].toLowerCase()) {
            donatorsList[i] = newName;
            break;
        }
    }
}
