name: Sync Fork (Force with Lease)

on:
  schedule:
    - cron: '*/30 * * * *'  # Every 30 minutes
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream repository
        run: |
          git remote add upstream https://github.com/dphdmn/openslidy.git || true
          git fetch upstream

      - name: Backup .github directory
        run: |
          rm -rf .github_backup
          cp -r .github .github_backup 2>/dev/null || true  # Silently fail if no .github

      - name: Reset to upstream exactly
        run: git reset --hard upstream/main

      - name: Restore .github directory
        run: |
          if [ -d ".github_backup" ]; then
            rm -rf .github
            mv .github_backup .github
          fi

      - name: Commit .github changes if needed
        run: |
          git add .github
          if ! git diff --cached --quiet; then
            git commit -m "Preserve .github directory after sync"
          fi

      - name: Force push with lease
        run: git push --force-with-lease origin main
